### PR TITLE
Pick 6

### PR DESCRIPTION
**Pull request by BoykinChas**
Pick 6 version 1 incomplete

### CODE REVIEW

**Review by chrisalv27 — COMMENTED** [review]
When I run your Pick6 lab nothing happens.  Look into how you're using your play100k function

**Comment by BoykinChas** [comment]
Yeah, I am running it now, and it is not working; trying to fix that not sure what happened. It worked the other day.

**Comment by BoykinChas** [comment]
I re pushed this i think

**Review by chrisalv27 — COMMENTED** [review]
Getting a "zeroDivisionerror" it looks like your expenses is staying at zero.  Look into calling your play100k function as well.

**Comment by BoykinChas** [comment]
Version 1 should work now.

**Review by chrisalv27 — APPROVED** [review]
Good job!

**Pull request merged**
